### ISSUE TITLE
npm run serve faild

### ISSUE THREAD

**Issue by cwx288270** [maomao1996/Vue-mmPlayer#12]
1、README
npm run dev //服务端运行 这个应该是写错了吧
2、npm run serve 后项目报错
$ npm run serve

> vue-mmplayer@1.5.6 serve F:\Vue-mmPlayer
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at config.plugin.tap.args (F:\Vue-mmPlayer\vue.config.js:19:14)
    at Object.tap (F:\Vue-mmPlayer\node_modules\webpack-chain\src\Plugin.js:24:24)
    at chainWebpack (F:\Vue-mmPlayer\vue.config.js:18:27)
    at webpackChainFns.forEach.fn (F:\Vue-mmPlayer\node_modules\@vue\cli-service\lib\Service.js:227:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (F:\Vue-mmPlayer\node_modules\@vue\cli-service\lib\Service.js:227:26)
    at Service.resolveWebpackConfig (F:\Vue-mmPlayer\node_modules\@vue\cli-service\lib\Service.js:231:48)
    at PluginAPI.resolveWebpackConfig (F:\Vue-mmPlayer\node_modules\@vue\cli-service\lib\PluginAPI.js:138:25)
    at serve (F:\Vue-mmPlayer\node_modules\@vue\cli-service\lib\commands\serve.js:48:31)
    at Service.run (F:\Vue-mmPlayer\node_modules\@vue\cli-service\lib\Service.js:221:12)
    at Object.<anonymous> (F:\Vue-mmPlayer\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-mmplayer@1.5.6 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-mmplayer@1.5.6 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
不知道作者本地有没有遇到此类问题

**Comment by maomao1996** [comment]
脚手架配置有点问题，现在已经修复了，你重新拉下代码就可以了
